apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: yongjia-express-sample-app
  app.kubernetes.io/instance: yongjia-express-sample-app-instance
  app.kubernetes.io/name: yongjia-express-sample-app-instance